### PR TITLE
Add windows sccache directory to search function

### LINKED ISSUE #90: sccache directory search algorithm incorrect on windows
mozilla/sccache lists the [local cache directory on windows](https://github.com/mozilla/sccache#local) as `%LOCALAPPDATA%\Mozilla\sccache`. The current algorithm uses `Mozilla.sccache` on MacOS **and `sccache` on any other OS.** This can easily be fixed by adding an `else if cfg!(target_os = "windows")` branch to the algorithm.

I can fix this in #89 if that would be easier.

### PR DESCRIPTION
**Pull request by Spaceface16518**
This pull request fixes #90

### CODE REVIEW

**Review by matthiaskrgr — APPROVED** [review]
Thanks.
Can you rebase (get rid of the merge) and squash the changes into a single commit please?

**Comment by Spaceface16518** [comment]
Hey sorry I never got back to this, but I'm not exactly sure how to do that since I've already committed the merge (stupid mistake, I know). Is there a way I can remove or rollback the changes so it regains the linear history?

**Review by Spaceface16518 — COMMENTED** [review]
Are you kidding me

**Comment by Spaceface16518** [comment]
I messed this up even more trying to do it. Should I just make a new branch and PR with the same changes?

**Comment by matthiaskrgr** [comment]
One way you could fix the branch is to:
Back up your branch:
`git checkout windows-sccache-dir`
`git branch windows-sccache-dir_backup` // this will crate a backup branch from the current state of checked out `windows-sccache-dir`

create a a new branch from master
`git checkout master`
`git branch windows-sccache-dir-2`
`git checkout windows-sccache-dir-2`
Cherry pick the needed changes into the new branch
`git cherry-pick --no-commit 8089924`
`git cherry-pick --no-commit 8a00005`
Commit the changes with `git commit` as a single commit
(The "Disable misreporting clippy lint" commit should not be needed anymore because the bug was fixed in clippy I think)

Then you remove the old `windows-sccache-dir` branch (which is ok since we have a backup).
`git branch -D windows-sccache-dir`
and rename the new `windows-sccache-dir-2` branch to the original branch name `git branch -m windows-sccache-dir-2 windows-sccache-dir` (basically we locally overwrite the branch with branch-2)

If you then force push (git push --force), the old changes of `windows-sccache-dir` will be overwritten with the new cleaned-up changes of `windows-sccache-dir-2` in this pull request and no seperate pull request is needed.

Alternatively you could `git rebase -i` and  [rewrite the branch history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) to change this branch as is without having to go the route of copying commits from one branch to another.

If you don't feel comfortable with messing around with branches that much I can clean up and merge the two commits myself which is also not a problem. :)

**Comment by Spaceface16518** [comment]
since this is a PR (so not a shared repo), i think i will use rebase to rewrite history. thank you, this was **very** helpful.

**Comment by Spaceface16518** [comment]
That worked perfectly! Thanks for the instructions!

Some CI checks are failing (rustfmt), but they aren't related to my code. I shouldn't worry about them, right?

**Comment by matthiaskrgr** [comment]
Great!

>Some CI checks are failing (rustfmt)

Oops, that's my fault! I didn't pay a lot of attention to CI because a bug in incremental compilation on nightly caused rustc to panic so ci was busted anyway. :sweat_smile:

**Pull request merged**
