### PR TITLE
Fix Windows CI issue and enable parallel deletion

### PR DESCRIPTION
**Pull request by rbtcollins**
- Fixes the Windows CI issue.
- enables parallel deletion when the rayon feature is enabled

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
:+1:

**Comment by matthiaskrgr** [comment]
I've sent out a collaborator invite so hopefully with that, PRs run ci automatically? :D
Need to catch some Zs now..

**Comment by rbtcollins** [comment]
@matthiaskrgr 

Failures seem to be related to running in nightly - linux is breaking, not just Windows. 

I got a clean run with the test branch content before putting this patch together.

**Comment by matthiaskrgr** [comment]
Yes, thank you!
I update the `remove_dir_all` dep and fixed the remaining tests that were not yet designed to expect a sparse registry index and ci is green again now! :partying_face:

**Pull request closed without merging**
